import type { Metadata } from "next";
// Import Geist fonts from Google Fonts directly
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavbarWrapper from "./component/NavbarWrapper";
import FooterWrapper from "./component/FooterWrapper";


// Use Google Fonts with preload disabled to avoid Turbopack issues
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  preload: false, // Disable preloading to avoid Turbopack issues
  display: 'swap',
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  preload: false, // Disable preloading to avoid Turbopack issues
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Only show Navbar if not in /admin route (client-side check) */}
        <NavbarWrapper />
        <main className="flex-grow">
          {children}
        </main>
        <FooterWrapper />
      </body>
    </html>
  );
}
